export const FETCH_USERS_BEGIN = 'FETCH_USERS_BEGIN';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const FETCH_AND_SET_USERS = "FETCH_AND_SET_USERS";

export const FETCH_SPECIFIC_USER_BEGIN = 'FETCH_SPECIFIC_USER_BEGIN';
export const FETCH_SPECIFIC_USER_SUCCESS = 'FETCH_SPECIFIC_USER_SUCCESS';
export const FETCH_SPECIFIC_USER_FAILURE = 'FETCH_SPECIFIC_USER_FAILURE';

export const REQ_INIT = "REQ_INIT";
export const REQ_FAIL = "REQ_FAIL";

export const FETCH_POKE_SUCCESS = "FETCH_POKE_SUCCESS";